[package]
name = "paillier"
version = "0.1.0"
authors = ["Isak Sunde Singh <isak.sunde.singh@gmail.com>"]
edition = "2018"

[dependencies]
num = { version = "0.2.1", features = ["rand"] }
rand = "0.5"
primes = "0.2.4"
glass_pumpkin = "0.3.3"
paste = "0.1.6"

[dev-dependencies]
proptest = "0.9.5"
